default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.2.9
    hooks:
      # Run the pip compile
      - id: pip-compile
        name: pip-compile requirements.txt
        files: pyproject.toml
        args: [ requirements.in, --resolver=backtracking, --upgrade, -q, -o, requirements.txt ]
