license_id: {{cookiecutter.license_id}}
methodology: {{cookiecutter.methodology}}
caveats: {{cookiecutter.caveats}}
dataset_source: {{cookiecutter.dataset_source}}
package_creator: HDX Data Systems Team
private: {{cookiecutter.private}}
maintainer: {{cookiecutter.dataset_maintainer}}
owner_org:  {{cookiecutter.dataset_organization}}
data_update_frequency: {{cookiecutter.dataset_expected_update_frequency}}
notes: {{cookiecutter.dataset_notes}}
